In [1]:
import numpy as np

In [2]:
a = np.arange(3) **3
print(a)

[0 1 8]


In [4]:
# 陣列的切片
print(a[-1])
print(a[0])
print(a[1:3])
print(a[-2:])   # 從-2取到結束

8
0
[1 8]
[1 8]


In [34]:
# 多維陣列取值用迭代 (用迴圈處理)
b1 = np.array([[[0,1],
                [2,3],
                [4,5]]])
print(b1)
print('='*60)
print('去掉最外的一層:')
for i in b1:
    print(i)
print('='*60)
print('去掉外面的二層:')
for i in b1:
    for j in i:
        print(j)
print('='*60)
print('把三層都去掉，將元素取出來:')
for i in b1:
    for j in i:
        for k in j:
            print(k)

[[[0 1]
  [2 3]
  [4 5]]]
去掉最外的一層:
[[0 1]
 [2 3]
 [4 5]]
去掉外面的二層:
[0 1]
[2 3]
[4 5]
把三層都去掉，將元素取出來:
0
1
2
3
4
5


In [21]:
# 如果要取元素，會先攤平再取
b2 = np.array([[[0,1],
                [2,3],
                [4,5]]])
b3 = b2.reshape(-1)
b4 = b2.flat
b5 = b2.flatten('C')
print('將陣列的元素取出來：')
for i in b3:
    print(i)
print('='*60)
for i in b4:
    print(i)
print('='*60)
for i in b5:
    print(i)

將陣列的元素取出來：
0
1
2
3
4
5
0
1
2
3
4
5
0
1
2
3
4
5


In [28]:
# 用 np.nditer 取元素
b3 = np.array([[[0,1],
                [2,3],
                [4,5]]])
print('='*60)
print('參數用C(默認值)，取元素依Row順序取')
for i in np.nditer(b3,order = 'C'):    
    print(i)
print('='*60)
print('參數用F，取元素依Column順序取')
for i in np.nditer(b3,order = 'F'):    
    print(i)

參數用C(默認值)，取元素依Row順序取
0
1
2
3
4
5
參數用F，取元素依Column順序取
0
2
4
1
3
5
